export const weatherCode = new Map([
  [
    0,
    {
      weather: "Clear Sky",
      iconDay: "clear-sky-day",
      iconNight: "clear-sky-night",
    },
  ],
  [
    1,
    {
      weather: "Mainly Clear",
      iconDay: "mainly-clear-day",
      iconNight: "mainly-clear-night",
    },
  ],
  [
    2,
    {
      weather: "Partly Cloudy",
      iconDay: "partly-clowdy-day",
      iconNight: "partly-clowdy-night",
    },
  ],
  [3, { weather: "Overcast", iconDay: "overcast" }],
  [45, { weather: "Fog", iconDay: "fog" }],
  [48, { weather: "Depositing rime fog", iconDay: "fog" }],
  [51, { weather: "Drizzle: Light", iconDay: "rain-moderate" }],
  [53, { weather: "Drizzle: Moderate", iconDay: "rain-moderate" }],
  [55, { weather: "Drizzle: Dense Intensity", iconDay: "rain-moderate" }],
  [56, { weather: "Freezing Drizzle: Light", iconDay: "rain-moderate" }],
  [
    57,
    { weather: "Freezing Drizzle: Dense Intensity", iconDay: "rain-moderate" },
  ],
  [61, { weather: "Rain: Slight", iconDay: "rain-slight" }],
  [63, { weather: "Rain: Moderate", iconDay: "rain-moderate" }],
  [65, { weather: "Rain: Heavy Intensity", iconDay: "rain-heavy" }],
  [66, { weather: "Freezing rain: Light", iconDay: "freezing-rain" }],
  [67, { weather: "Freezing rain: Heavy intensity", iconDay: "freezing-rain" }],
  [71, { weather: "Snow fall: Slight", iconDay: "snow" }],
  [73, { weather: "Snow fall: Moderate", iconDay: "snow" }],
  [75, { weather: "Snow fall: Heavy intensity", iconDay: "snow" }],
  [77, { weather: "Snow Grains", iconDay: "snow" }],
  [80, { weather: "Rain Showers: Slight", iconDay: "rain-slight" }],
  [81, { weather: "Rain Showers: Moderate", iconDay: "rain-moderate" }],
  [82, { weather: "Rain Showers: Violent", iconDay: "storm" }],
  [85, { weather: "Snow Showers: Slight", iconDay: "snow" }],
  [86, { weather: "Snow Showers: Heavy", iconDay: "snow" }],
  [95, { weather: "Thunderstorm: Slight or Moderate", iconDay: "storm" }],
  [96, { weather: "Thunderstorm with heavy hail", iconDay: "storm" }],
  [99, { weather: "Thunderstorm with slight hail", iconDay: "hailstorm" }],
]);

export const locations = [
  "bucuresti",
  "pitesti",
  "craiova",
  "constanta",
  "brasov",
  "sibiu",
  "cluj-napoca",
  "iasi",
  "targu jiu",
  "ramnicu valcea",
  "ploiesti",
  "buzau",
  "galati",
  "focsani",
  "bacau",
  "suceava",
  "botosani",
  "piatra neamt",
  "timisoara",
];
